import { ReactNode } from 'react';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/favicon.ico', href: '/favicon.ico' }],
  },
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
