import { ReactNode } from 'react';
import { Toaster } from 'react-hot-toast';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import { Sidebar } from '@/components/sidebar';

import { cn } from '@/lib/utils';

import './globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/favicon.ico', href: '/favicon.ico' }],
  },
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={cn('flex min-h-screen bg-[#343541] font-sans antialiased', fontSans.variable)}
      >
        <Sidebar />
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
};

export default RootLayout;
